#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Format all selected files
echo "$FILES" | xargs bunx @biomejs/biome@1 format --write

# Biome check and lint all selected files
echo "$FILES" | xargs bunx @biomejs/biome@1 check --apply

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0